<?php
declare(strict_types=1);

return [
    'admin' => [
        'code' => 'admin',
        'title' => 'Neptune Administrator Operations CBT',
        'short_title' => 'Admin CBT',
        'module' => 'SATURN · Administration & Event Operations',
        'version' => '1.2',
        'passing_score' => 85,
        'question_count' => 20,
        'access_roles' => [
            'owner',
            'admin',
        ],
        'description' => 'Scenario-based certification for administrators who manage users and access, create events, recover from TBA/schedule problems, run Match Control, protect scouting data quality, and understand platform-owner maintenance boundaries.',
        'briefing' => [
            'Use the newest verified official event information. When TBA is late, the verified paper schedule can drive the same Neptune event through the manual workflow.',
            'Protect robot identity and station assignments before protecting completeness. Do not guess schedule data or scouting actions.',
            'Re-scout is for a new/clean run; isolated mistakes should be corrected at the action level.',
            'Treat predictions and EPA as evidence with confidence limits, not as unquestionable facts.',
            'Use Teams & Users for normal account administration and recovery. Routine password problems should not require direct MySQL edits.',
            'Platform-wide tenant suspension, owner reset, tenant export, filesystem access, and update/migration history are platform-owner responsibilities, not ordinary organization-admin permissions.',
        ],
        'questions' => [
            [
                'id' => 'adm01',
                'question' => 'At 7:20 AM the event hands your team a printed qualification schedule, but TBA still shows no matches. Pit scouting is already attached to the Neptune event. What should the admin do?',
                'options' => [
                    'a' => 'Keep the existing event, enter/verify the event robots, manually build every official paper-schedule match with all six stations, then have the schedule cross-checked before live scouting.',
                    'b' => 'Create a second event named “Manual Schedule” so TBA cannot overwrite the first event.',
                    'c' => 'Wait for TBA before making any match available to scouts.',
                    'd' => 'Enter only your own team\'s matches and add the rest if needed later.',
                ],
                'correct' => 'a',
                'explanation' => 'The manual fallback keeps the same Neptune event operational. The official paper schedule becomes the source of truth until TBA catches up; all station assignments should be entered and verified because every robot\'s scouting record depends on them.',
            ],
            [
                'id' => 'adm02',
                'question' => 'You are manually entering Qual 18 from the official paper schedule. Red 2 is smudged and could be either 5411 or 5417. What is the correct action?',
                'options' => [
                    'a' => 'Choose the team that appears most often near Qual 18.',
                    'b' => 'Leave/hold that assignment until the official source is verified; do not guess.',
                    'c' => 'Use the lower team number because FIRST schedules are sorted.',
                    'd' => 'Assign either team and ask the scout to correct it during the match.',
                ],
                'correct' => 'b',
                'explanation' => 'A wrong station assignment contaminates an entire robot\'s match record. Ambiguous schedule data must be verified from an official source, not inferred.',
            ],
            [
                'id' => 'adm03',
                'question' => 'TBA publishes the event three hours after you manually built the schedule and Neptune already contains pit data and 12 scouted matches. What is the best next step?',
                'options' => [
                    'a' => 'Delete the manual event and re-import the TBA event.',
                    'b' => 'Create a fresh TBA event and copy only the final scores.',
                    'c' => 'Link/sync TBA to the same Neptune event, preserve its event ID, and reconcile any official schedule revisions.',
                    'd' => 'Never sync TBA once manual matches exist.',
                ],
                'correct' => 'c',
                'explanation' => 'Neptune supports linking an official TBA event to an existing manual event so the same event ID and attached scouting data are preserved.',
            ],
            [
                'id' => 'adm04',
                'question' => 'The official paper schedule has been revised after a field delay. TBA still shows the old version. Which source should drive the next matches?',
                'options' => [
                    'a' => 'The newest verified official schedule from the event, with affected Neptune matches corrected and spot-checked.',
                    'b' => 'TBA, because online data always outranks paper.',
                    'c' => 'Whichever schedule gives your team the easier opponents.',
                    'd' => 'Keep the old schedule until both sources agree.',
                ],
                'correct' => 'a',
                'explanation' => 'A newly issued official schedule supersedes an older copy. Neptune should reflect the currently authoritative schedule even if TBA has not caught up yet.',
            ],
            [
                'id' => 'adm05',
                'question' => 'Match Control will not allow Make Ready because the match has zero attached robots. What must be fixed?',
                'options' => [
                    'a' => 'The match\'s six station assignments must be loaded or verified from TBA or the official manual schedule.',
                    'b' => 'The official final score must be entered first.',
                    'c' => 'At least one scout must already be connected.',
                    'd' => 'The event must have a TBA key.',
                ],
                'correct' => 'a',
                'explanation' => 'Make Ready depends on match_teams being present. Those assignments may come from TBA or the verified manual schedule; a TBA key or score is not required.',
            ],
            [
                'id' => 'adm06',
                'question' => 'An FRC match is officially replayed. The original Neptune run contains valid scouting data but must not count as the result of the replay. What should Command do?',
                'options' => [
                    'a' => 'Delete the match and recreate it with the same number.',
                    'b' => 'Use Re-scout / Ready Again so Neptune starts a new run and voids the prior run from normal analytics while retaining audit history.',
                    'c' => 'Start the ended match without changing its run.',
                    'd' => 'Keep both runs active and let Strategy average them.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune\'s re-scout workflow increments the run, closes prior sessions, and soft-voids the old run so normal analytics use the new run without destroying history.',
            ],
            [
                'id' => 'adm07',
                'question' => 'A scout accidentally records one successful scoring action that never happened. Everything else in the match is correct. What is the least destructive correction?',
                'options' => [
                    'a' => 'Re-scout the entire match.',
                    'b' => 'Edit the official FRC score to compensate.',
                    'c' => 'Remove/soft-delete the specific bad action through the administrative action history/correction workflow.',
                    'd' => 'Add a fake Failure action for the same number of points.',
                ],
                'correct' => 'c',
                'explanation' => 'A single bad action should be corrected at the action level. Re-scouting is for a bad run, not one isolated entry, and fabricated compensating actions create additional bad data.',
            ],
            [
                'id' => 'adm08',
                'question' => 'Command clicks Start about 12 seconds after the actual field match begins. Scouts have otherwise followed the robots correctly. What is the most defensible response?',
                'options' => [
                    'a' => 'Start Neptune immediately, tell Strategy the timing metrics are shifted, and only reconstruct timing later from reliable video if the mismatch makes timing analysis unusable.',
                    'b' => 'Do not start Neptune at all; enter a perfect match from memory afterward.',
                    'c' => 'Start Neptune and tell scouts to enter twelve seconds of fake actions to catch up.',
                    'd' => 'Change all recorded timestamps directly in the database during the event.',
                ],
                'correct' => 'a',
                'explanation' => 'The priority is to preserve observed actions while clearly flagging degraded timing quality. If timing is critical and reliable video exists, a controlled re-entry can be considered.',
            ],
            [
                'id' => 'adm09',
                'question' => 'TBA has not posted the final score for Qual 31, but Neptune\'s scouts completed the match. What should the admin do?',
                'options' => [
                    'a' => 'Change scouting actions until Neptune\'s point total equals the field score estimate.',
                    'b' => 'Keep the scouting record intact and refresh/sync official scores later.',
                    'c' => 'Delete the match because official confirmation is missing.',
                    'd' => 'Mark every uncertain scout action as Failure.',
                ],
                'correct' => 'b',
                'explanation' => 'Scouting observations and official match results are different data sources. A delayed official score is not a reason to rewrite what scouts observed.',
            ],
            [
                'id' => 'adm10',
                'question' => 'TBA becomes unreachable for 45 minutes after the full schedule has already been loaded. Which operating mode is preferred?',
                'options' => [
                    'a' => 'Pause all scouting until TBA returns.',
                    'b' => 'Continue with Neptune\'s loaded schedule/local operations and use verified paper information for changes; sync TBA later.',
                    'c' => 'Create a temporary second database.',
                    'd' => 'Ask scouts to use TBA on their phones instead of Neptune.',
                ],
                'correct' => 'b',
                'explanation' => 'TBA is an external data source, not the live-control dependency for a schedule Neptune already has. Event operations should continue from verified local/manual data.',
            ],
            [
                'id' => 'adm11',
                'question' => 'A scout\'s phone briefly loses Wi-Fi during a running match, but the Traditional Scouting interface remains open. What should Command tell the scout?',
                'options' => [
                    'a' => 'Refresh repeatedly until the page reconnects.',
                    'b' => 'Clear browser storage so old actions cannot duplicate.',
                    'c' => 'Keep scouting, allow Neptune\'s temporary request queue to protect entries, reconnect, and verify that queued actions synchronize.',
                    'd' => 'Stop observing until Wi-Fi returns.',
                ],
                'correct' => 'c',
                'explanation' => 'Traditional Scouting includes IndexedDB request protection for short interruptions. Refreshing or clearing site data risks losing the queued state.',
            ],
            [
                'id' => 'adm12',
                'question' => 'At Ready, one of six Traditional scouts is absent and no immediate replacement is available. What is the best fallback?',
                'options' => [
                    'a' => 'Have another scout invent the missing robot\'s actions from the alliance score.',
                    'b' => 'Prioritize critical robot coverage, assign a backup if one becomes available, and document the coverage gap rather than fabricate data.',
                    'c' => 'Duplicate one scout\'s existing robot data under the missing team\'s number.',
                    'd' => 'Cancel scouting for all six robots.',
                ],
                'correct' => 'b',
                'explanation' => 'Incomplete but honest data is more useful than fabricated completeness. Coverage gaps should be explicit so Strategy can discount confidence.',
            ],
            [
                'id' => 'adm13',
                'question' => 'A scout realizes before Start that their station card shows the wrong robot compared with the official schedule. What should happen?',
                'options' => [
                    'a' => 'Let the match start; the scout can mentally follow the correct robot while Neptune records the assigned one.',
                    'b' => 'Stop and correct the match/station assignment before the run starts.',
                    'c' => 'Swap the robot number after the match without telling anyone.',
                    'd' => 'Use Tag Scouting instead because it does not require robot identity.',
                ],
                'correct' => 'b',
                'explanation' => 'Robot identity is foundational. Correcting it before Start prevents a full match of valid observations being attached to the wrong team.',
            ],
            [
                'id' => 'adm14',
                'question' => 'A scout followed the wrong robot for almost an entire match. The action sequence is internally consistent but belongs to another team. What is the best data-quality response?',
                'options' => [
                    'a' => 'Keep it because the action sequence itself is accurate.',
                    'b' => 'Relabel the actions to whichever robot seems most likely.',
                    'c' => 'Treat the run as contaminated; remove/void the bad data and only re-enter from reliable video or another defensible source.',
                    'd' => 'Average the bad run with Tag Scouting to reduce its effect.',
                ],
                'correct' => 'c',
                'explanation' => 'A coherent record attached to the wrong robot is still bad data. It should not remain in analytics simply because the clicks were consistent.',
            ],
            [
                'id' => 'adm15',
                'question' => 'The Neptune server is unreachable during three matches. Your backup procedure captures paper observations with robot identity and match numbers. When the server returns, what should you enter?',
                'options' => [
                    'a' => 'Only observations that can be defensibly reconstructed, preserving identity and context; do not invent missing detail.',
                    'b' => 'Estimate every action so all matches look complete.',
                    'c' => 'Copy the closest earlier match for each robot.',
                    'd' => 'Skip all three matches even if the paper record is reliable.',
                ],
                'correct' => 'a',
                'explanation' => 'A backup workflow can preserve useful data, but the reconstruction must stay inside what was actually captured. Precision should not be fabricated after the fact.',
            ],
            [
                'id' => 'adm16',
                'question' => 'Public EPA is missing for a robot that has strong current-event scouting. How should Strategy/Admin interpret that?',
                'options' => [
                    'a' => 'The robot is probably weak because EPA is blank.',
                    'b' => 'Use available scouting, prior-event data, and direct observation while lowering model confidence; missing EPA is not a performance verdict.',
                    'c' => 'Remove the robot from Alliance Selection.',
                    'd' => 'Replace EPA with pit-reported maximum score.',
                ],
                'correct' => 'b',
                'explanation' => 'Public EPA is one signal. Missing or stale public data should reduce confidence in that signal, not be treated as negative robot performance.',
            ],
            [
                'id' => 'adm17',
                'question' => 'Pit scouting says a robot has a reliable endgame. In its first four matches, it attempts endgame three times and fails all three. How should Neptune users handle the conflict?',
                'options' => [
                    'a' => 'Delete the pit claim because it is now proven false.',
                    'b' => 'Ignore the match failures because pit data came directly from the team.',
                    'c' => 'Retain both claimed and observed information; use the observed failures as stronger current-event evidence and flag reliability.',
                    'd' => 'Average the statements into a 50% success rate even though one is not an observation.',
                ],
                'correct' => 'c',
                'explanation' => 'Pit scouting often captures claimed capability; match scouting captures observed execution. Keeping both preserves context while allowing Strategy to weight current observed evidence more heavily.',
            ],
            [
                'id' => 'adm18',
                'question' => 'Why is selecting the correct Current Event important before competition operations?',
                'options' => [
                    'a' => 'It changes every user\'s password policy.',
                    'b' => 'It keeps event-scoped pages, schedules, pit/pre data, and operational context pointed at the event the team is actually working.',
                    'c' => 'It forces TBA to publish scores sooner.',
                    'd' => 'It permanently archives all other events.',
                ],
                'correct' => 'b',
                'explanation' => 'Current Event is an operational context selector. A wrong current event can make users think data is missing or cause them to work in the wrong event context.',
            ],
            [
                'id' => 'adm19',
                'question' => 'Which statement best describes Neptune\'s roster sync and schedule sync?',
                'options' => [
                    'a' => 'They are the same operation; a roster cannot exist without matches.',
                    'b' => 'They are independent enough that pit/pre work can begin from a roster before qualification matches are published.',
                    'c' => 'Schedule sync must always happen before roster sync.',
                    'd' => 'Manual rosters are prohibited once TBA is linked.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune can use an event roster before a match schedule exists, which keeps pre-scouting and pit scouting productive while waiting for official match assignments.',
            ],
            [
                'id' => 'adm20',
                'question' => 'You click Start on Qual 42 while another match on the same Neptune field is still marked Running. What does current Match Control do?',
                'options' => [
                    'a' => 'It refuses to start Qual 42 under all circumstances.',
                    'b' => 'It automatically marks the other running/paused match on that field ended, then starts Qual 42.',
                    'c' => 'It runs both matches simultaneously.',
                    'd' => 'It deletes the earlier match.',
                ],
                'correct' => 'b',
                'explanation' => 'Current Match Control closes another running/paused match on the same field when a new match is started, preventing two simultaneous active clocks on one field.',
            ],
            [
                'id' => 'adm21',
                'question' => 'An active Neptune match run is intentionally paused because live field action has temporarily stopped, and the same run will continue rather than be replayed from the beginning. Which Match Control sequence fits that situation?',
                'options' => [
                    'a' => 'End and Re-scout.',
                    'b' => 'Pause, then Resume when live field action continues.',
                    'c' => 'Delete the match.',
                    'd' => 'Create a new qualification match number.',
                ],
                'correct' => 'b',
                'explanation' => 'Pause/Resume preserves the same scouting run while accounting for a temporary halt. Re-scout / Ready Again is for a new clean run, such as an official replay, not a continuation of the same run.',
            ],
            [
                'id' => 'adm22',
                'question' => 'What does End do to the current scouting run?',
                'options' => [
                    'a' => 'It preserves the run as the completed scouting record.',
                    'b' => 'It automatically voids all actions.',
                    'c' => 'It converts every action to Neutral.',
                    'd' => 'It immediately creates run 2.',
                ],
                'correct' => 'a',
                'explanation' => 'End closes the match while preserving the current run. A new run is created only when an ended match is deliberately made Ready again for re-scouting.',
            ],
            [
                'id' => 'adm23',
                'question' => 'Before the first event of a new game, which validation is most important for the live Traditional Scouting interface?',
                'options' => [
                    'a' => 'Confirm the Game Builder\'s timing, phases, action definitions, points, and button layout match the intended game/scouting method.',
                    'b' => 'Only confirm the Neptune logo is visible.',
                    'c' => 'Wait for the first official match and correct the configuration live.',
                    'd' => 'Use last year\'s game JSON until TBA identifies the new game.',
                ],
                'correct' => 'a',
                'explanation' => 'Traditional Scouting renders from the game configuration. Incorrect actions or timing can systematically corrupt every match, so they must be tested before live use.',
            ],
            [
                'id' => 'adm24',
                'question' => 'What is Live Monitor primarily for during event operations?',
                'options' => [
                    'a' => 'Replacing the scouts by calculating actions from the final score.',
                    'b' => 'Watching connected scouts, robot assignments, actions, and current match state so Command can catch coverage or connection problems.',
                    'c' => 'Editing TBA\'s official schedule.',
                    'd' => 'Changing Public EPA values manually.',
                ],
                'correct' => 'b',
                'explanation' => 'Live Monitor is Command\'s operational visibility layer. It helps catch missing sessions, wrong assignments, or lack of incoming actions while a match is active.',
            ],
            [
                'id' => 'adm25',
                'question' => 'Ten minutes before your team\'s match, AUGUR predicts a 68% win probability but the data-confidence block shows only one scouted match for a key partner and incomplete pit data. What should Strategy do?',
                'options' => [
                    'a' => 'Treat 68% as a precise probability and ignore the confidence information.',
                    'b' => 'Use the prediction as one signal, explicitly discount certainty, inspect Robot Intelligence/observations, and build a plan robust to the missing data.',
                    'c' => 'Round 68% to 100% because your alliance is favored.',
                    'd' => 'Disable Match Strategy until every robot has five matches.',
                ],
                'correct' => 'b',
                'explanation' => 'Predictions are only as useful as their evidence. The confidence and coverage context should influence how strongly Strategy relies on a numerical forecast.',
            ],
            [
                'id' => 'adm26',
                'question' => 'Which statement correctly distinguishes Public EPA from Neptune EPA?',
                'options' => [
                    'a' => 'They are always the same value displayed in two places.',
                    'b' => 'Public EPA is Neptune\'s public-data rating layer; Neptune EPA is an organization-private offensive strength estimate that blends public baseline with the organization\'s observed scouting factors.',
                    'c' => 'Neptune EPA is the official FIRST ranking score.',
                    'd' => 'Public EPA includes your private pit notes by default.',
                ],
                'correct' => 'b',
                'explanation' => 'The two ratings have different data scopes. Public EPA comes from the public data layer; Neptune EPA can incorporate your organization\'s observed scouting performance.',
            ],
            [
                'id' => 'adm27',
                'question' => 'A manual qualification schedule has 54 matches. What is the strongest verification method before live scouting begins?',
                'options' => [
                    'a' => 'Check only Qual 1; if it is correct the rest must be correct.',
                    'b' => 'Have a second person cross-check the full manual schedule against the official paper copy, including every match number and all six Red/Blue station assignments, with special attention to your own team\'s matches.',
                    'c' => 'Ask each scout to correct errors as they notice them during live matches.',
                    'd' => 'Compare only match numbers, not robot stations.',
                ],
                'correct' => 'b',
                'explanation' => 'A station-level transcription error can attach an entire scouting stream to the wrong robot. A second-person full cross-check is stronger than a small spot-check and is the preferred standard before live operation.',
            ],
            [
                'id' => 'adm28',
                'question' => 'TBA lists an event that closely resembles your manually created event, but the match is ambiguous between two similarly named events. What should an admin do?',
                'options' => [
                    'a' => 'Auto-link the first result to save time.',
                    'b' => 'Verify the correct official event and explicitly link it; do not allow a weak/ambiguous match to modify the event.',
                    'c' => 'Delete both manual events.',
                    'd' => 'Link both TBA event keys to the same Neptune event.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune intentionally avoids weak automatic event linking. A wrong link can rewrite event identity and schedule data, so ambiguity requires human verification.',
            ],
            [
                'id' => 'adm29',
                'question' => 'A coach asks you to install an untested feature patch during qualification matches because it adds a useful chart. What is the best operations decision?',
                'options' => [
                    'a' => 'Install it immediately; backups make live risk irrelevant.',
                    'b' => 'Avoid unnecessary production changes during active competition; defer until a controlled window unless the patch fixes a critical operational failure.',
                    'c' => 'Install it only on scouts\' phones.',
                    'd' => 'Modify PHP directly in File Manager without a backup.',
                ],
                'correct' => 'b',
                'explanation' => 'Live competition favors stability. Neptune\'s patch/rollback tools reduce risk but do not eliminate the possibility of disrupting scouting during a match block.',
            ],
            [
                'id' => 'adm30',
                'question' => 'A schedule correction changes Blue 3 in Qual 27 after that match is already marked Ready but before Start. What should Command do?',
                'options' => [
                    'a' => 'Start the match because Ready locks the schedule.',
                    'b' => 'Correct the assignment to the newest official schedule, verify the six teams, and only then proceed with the correct match.',
                    'c' => 'Tell Blue 3\'s scout to follow the new robot while leaving Neptune on the old team.',
                    'd' => 'Use the old schedule until the next event day.',
                ],
                'correct' => 'b',
                'explanation' => 'Ready is not permission to knowingly scout the wrong assignment. Correct identity before the run starts so sessions/actions attach to the correct robot.',
            ],
            [
                'id' => 'adm31',
                'question' => 'Why should an admin avoid creating a duplicate event when switching from manual operation to TBA?',
                'options' => [
                    'a' => 'Because Neptune only allows one event per season globally.',
                    'b' => 'Because pit, pre-scout, match history, strategy records, and current-event context can split across event IDs, weakening analytics and confusing users.',
                    'c' => 'Because TBA rejects duplicate local events.',
                    'd' => 'Because duplicate events automatically delete users.',
                ],
                'correct' => 'b',
                'explanation' => 'The goal of manual-to-TBA linking is continuity. Keeping one event ID prevents event-scoped data from being fragmented.',
            ],
            [
                'id' => 'adm32',
                'question' => 'During schedule entry, an admin has entered all six teams for a match but accidentally placed Red 1 at Red 2 and vice versa. Why is this still serious if both robots are on the correct alliance?',
                'options' => [
                    'a' => 'It is not serious; alliance color is the only field scouts use.',
                    'b' => 'Traditional scouts select field stations, so the station mapping determines which robot each scout is assigned and can attach an entire observation stream to the wrong team.',
                    'c' => 'It only affects the displayed match score.',
                    'd' => 'It changes Public EPA for the whole event.',
                ],
                'correct' => 'b',
                'explanation' => 'TRIDENT assigns the robot from alliance plus station. A station swap can silently cross-label two full scouting streams even when alliance color is right.',
            ],
            [
                'id' => 'adm33',
                'question' => 'A match contains excellent Traditional data from four robots, Tag Match observations from all six, and no Traditional coverage for two. How should Strategy treat the missing Traditional robots?',
                'options' => [
                    'a' => 'Pretend Tag scoring share is equivalent to action-by-action points and fill the missing Traditional rows.',
                    'b' => 'Keep the Traditional coverage gap explicit and review the Tag observations separately as supporting evidence; do not treat Tag data as if it populated AUGUR/Traditional metrics.',
                    'c' => 'Delete Tag data because it is not Traditional.',
                    'd' => 'Copy the two robots\' pit capabilities into match actions.',
                ],
                'correct' => 'b',
                'explanation' => 'Tag and Traditional scouting are different evidence types. Tag observations can inform a human strategy discussion, but Tag data is not currently a substitute for missing Traditional actions and does not populate AUGUR analytics or prediction inputs.',
            ],
            [
                'id' => 'adm34',
                'question' => 'Your team is running two simultaneous fields at a championship-style event. Which administrative principle matters most?',
                'options' => [
                    'a' => 'Use one active Match Control state for both physical fields and ignore field IDs.',
                    'b' => 'Maintain correct field IDs, assignments, and command ownership so starting/ending one field does not accidentally interfere with the other field\'s match state.',
                    'c' => 'Use only Tag Scouting on the second field.',
                    'd' => 'Duplicate the organization for the second field.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune\'s match state is field-aware. Multi-field operation requires disciplined field assignment and Command coordination so each field\'s live state remains independent.',
            ],
            [
                'id' => 'adm35',
                'question' => 'A mentor in your organization forgot their Neptune password the morning of an event. What is the normal administrative recovery path?',
                'options' => [
                    'a' => 'Edit the users table directly in MySQL.',
                    'b' => 'Use Teams & Users to issue a temporary password, or have the user use Google-verified Forgot Password when available.',
                    'c' => 'Create a second user with the same identity and merge the records later.',
                    'd' => 'Disable CSRF protection so the user can bypass login.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune account self-service is designed to keep routine recovery out of MySQL. Owners/admins can issue a temporary password, while Forgot Password can verify the user through Google.',
            ],
            [
                'id' => 'adm36',
                'question' => 'An owner of another Neptune organization asks an ordinary organization admin to suspend a different tenant and export that tenant\'s data. What should happen?',
                'options' => [
                    'a' => 'The admin should use Database Lab to update the organizations table.',
                    'b' => 'Those are platform-owner actions performed from Platform Administration; ordinary tenant admins remain organization-scoped.',
                    'c' => 'The admin should use File Manager to delete the other tenant.',
                    'd' => 'Any owner can manage every organization because owners are globally privileged.',
                ],
                'correct' => 'b',
                'explanation' => 'Neptune separates organization administration from installation-wide platform administration. Tenant suspension/reactivation, owner reset, cross-tenant details, and tenant export belong to the designated platform organization owner.',
            ],
            [
                'id' => 'adm37',
                'question' => 'A Maintenance Console patch updates PHP files and applies a schema change. What should the maintainer expect Neptune to record?',
                'options' => [
                    'a' => 'Only the ZIP filename; database changes are intentionally invisible.',
                    'b' => 'Files updated plus the applied migration key/package in neptune_migrations. A later file rollback does not automatically reverse the DB migration.',
                    'c' => 'A full automatic database downgrade script for every patch.',
                    'd' => 'Nothing unless the maintainer manually edits the database.',
                ],
                'correct' => 'b',
                'explanation' => 'Current schema-changing updates use tracked self-migrations. Maintenance Console exposes both file-update and DB-migration history, while schema rollback remains deliberately separate from file rollback.',
            ],
        ],
    ],
    'scouter' => [
        'code' => 'scouter',
        'title' => 'Neptune Scouter Certification CBT',
        'short_title' => 'Scouter CBT',
        'module' => 'TRIDENT · Scouting',
        'version' => '1.1',
        'passing_score' => 85,
        'question_count' => 20,
        'access_roles' => [
            'owner',
            'admin',
            'strategy',
            'scout',
        ],
        'description' => 'Scenario-based certification covering Traditional Match Scouting, Tag Scouting, data quality, offline behavior, and how scouting evidence should be handed to Strategy.',
        'briefing' => [
            'Traditional Scouting follows one assigned robot for the entire match. Right = Success; left = Failure; unknown = do not guess.',
            'Tag Scouting is the unified quick-observation system. Its Match context records scoring share, tags/weights, and notes; Pit and Team contexts capture quick contextual observations and media.',
            'Tag records are collected and stored separately; they do not currently populate AUGUR analytics, EPA, predictions, or Traditional action metrics.',
            'Brief network loss is not permission to abandon the robot or clear the browser. Preserve the session and verify sync after reconnecting.',
            'Honest missing data is better than fabricated completeness.',
        ],
        'questions' => [
            [
                'id' => 'sct01',
                'question' => 'You are assigned Blue 2. During the match, Blue 1 scores while your robot is crossing the field. What should you record?',
                'options' => [
                    'a' => 'The score, because your alliance benefited.',
                    'b' => 'Nothing for that score; Traditional Scouting follows your assigned robot, not the alliance.',
                    'c' => 'Half the score because Blue 1 and Blue 2 are partners.',
                    'd' => 'A Neutral action for your robot.',
                ],
                'correct' => 'b',
                'explanation' => 'Traditional Scouting is one-robot observation. Alliance-partner actions must not be attributed to the robot you are assigned.',
            ],
            [
                'id' => 'sct02',
                'question' => 'Your robot attempts a configured scoring action and clearly misses. Which gesture records the attempt correctly?',
                'options' => [
                    'a' => 'Swipe right for Success.',
                    'b' => 'Swipe left for Failure.',
                    'c' => 'Do not record failed attempts.',
                    'd' => 'Tap Disabled.',
                ],
                'correct' => 'b',
                'explanation' => 'TRIDENT uses right-swipe Success and left-swipe Failure. Failed attempts are meaningful evidence and should be captured when observed.',
            ],
            [
                'id' => 'sct03',
                'question' => 'You look away for two seconds and hear cheering. When you look back, your robot is driving away from the scoring area. You did not see whether it scored. What should you do?',
                'options' => [
                    'a' => 'Record Success because the crowd cheered.',
                    'b' => 'Record Failure because you did not see a score.',
                    'c' => 'Do not guess; continue observing from the next action you can confidently identify.',
                    'd' => 'Ask the scout next to you and copy whatever they entered without checking which robot they follow.',
                ],
                'correct' => 'c',
                'explanation' => 'Unknown is not the same as Success or Failure. Missing one action is less harmful than adding a confident-looking false observation.',
            ],
            [
                'id' => 'sct04',
                'question' => 'The same action button needs to be recorded three times in quick succession. What is the intended Traditional Scouting behavior?',
                'options' => [
                    'a' => 'Neptune supports repeated swipes of the same action without requiring you to reopen the action dialog every time.',
                    'b' => 'Only the first action should be recorded.',
                    'c' => 'Refresh the page between every action.',
                    'd' => 'Combine all three into one action with triple points.',
                ],
                'correct' => 'a',
                'explanation' => 'The live scouting interface supports repeated entry of the same configured action, which is important for rapid game events.',
            ],
            [
                'id' => 'sct05',
                'question' => 'Before Start, your screen says Red 3 #4123, but the official field lineup shows Red 3 #4132. What should you do?',
                'options' => [
                    'a' => 'Scout #4132 but leave Neptune assigned to #4123.',
                    'b' => 'Immediately notify Command and get the station assignment corrected before the match starts.',
                    'c' => 'Scout whichever robot is closer to you.',
                    'd' => 'Wait until after the match to mention it.',
                ],
                'correct' => 'b',
                'explanation' => 'Correct robot identity before Start. Otherwise even accurate clicks will be stored under the wrong team number.',
            ],
            [
                'id' => 'sct06',
                'question' => 'Thirty seconds into a match, you realize you have been watching the wrong robot. What is the best immediate action?',
                'options' => [
                    'a' => 'Silently switch to the correct robot and leave the first 30 seconds unchanged.',
                    'b' => 'Notify Command as soon as practical and clearly identify that the run is contaminated; do not invent a correction from memory.',
                    'c' => 'Change every earlier action to Failure.',
                    'd' => 'Keep following the wrong robot so the dataset is internally consistent.',
                ],
                'correct' => 'b',
                'explanation' => 'Wrong-robot data needs administrative correction. Quietly switching creates a mixed record that looks valid but describes two different machines.',
            ],
            [
                'id' => 'sct07',
                'question' => 'Your Wi-Fi drops briefly but the match page remains visible and responsive enough to keep entering actions. What should you do?',
                'options' => [
                    'a' => 'Keep scouting; Neptune can queue temporary Traditional requests, then verify synchronization after reconnecting.',
                    'b' => 'Immediately clear browser data.',
                    'c' => 'Close the browser so it cannot save stale information.',
                    'd' => 'Stop observing the robot.',
                ],
                'correct' => 'a',
                'explanation' => 'The offline protection is designed for short network interruptions. Keeping the session open preserves queued requests and your continuity of observation.',
            ],
            [
                'id' => 'sct08',
                'question' => 'Why is repeatedly refreshing the scouting page during a brief network interruption a poor response?',
                'options' => [
                    'a' => 'It can disrupt the session/queued request state and distract you from the robot.',
                    'b' => 'Refreshes permanently lower Public EPA.',
                    'c' => 'Refreshes change your FRC team number.',
                    'd' => 'There is no downside; refresh should be used after every action.',
                ],
                'correct' => 'a',
                'explanation' => 'The match is still happening while you troubleshoot. Avoid actions that risk local queued state or cause you to miss the robot you are responsible for following.',
            ],
            [
                'id' => 'sct09',
                'question' => 'An official replay is announced after you already scouted the original match. What should you expect?',
                'options' => [
                    'a' => 'Command will use Re-scout / Ready Again, and you should scout the new run as a fresh observation when assigned.',
                    'b' => 'You should edit the old run until it resembles the replay.',
                    'c' => 'Both runs will always be averaged equally in normal analytics.',
                    'd' => 'The replay should not be scouted.',
                ],
                'correct' => 'a',
                'explanation' => 'A replay is a new official run. Neptune preserves audit history but excludes the superseded run from normal analytics after Command initiates re-scouting.',
            ],
            [
                'id' => 'sct10',
                'question' => 'You accidentally swipe Success for an action that was actually a Failure. What should you do?',
                'options' => [
                    'a' => 'Add a fake Failure action to cancel the points.',
                    'b' => 'Tell Command/admin promptly so the specific bad action can be corrected; do not create compensating fake data.',
                    'c' => 'Ignore it because one action cannot matter.',
                    'd' => 'Re-scout the entire match on your own.',
                ],
                'correct' => 'b',
                'explanation' => 'A known bad action should be corrected explicitly. Adding invented compensating actions makes the event history less trustworthy.',
            ],
            [
                'id' => 'sct11',
                'question' => 'The official alliance score is 20 points higher than the total you see on your scouting display. What should you do?',
                'options' => [
                    'a' => 'Add enough successful actions to make the totals match.',
                    'b' => 'Continue recording only what your assigned robot actually does; scouting totals are not required to equal the official alliance score.',
                    'c' => 'Change every Failure to Success.',
                    'd' => 'Stop scouting until Command explains the score gap.',
                ],
                'correct' => 'b',
                'explanation' => 'Official alliance scores can include partners, bonuses, penalties, or game elements your robot did not cause. Traditional data should reflect observation, not reconciliation to a scoreboard.',
            ],
            [
                'id' => 'sct12',
                'question' => 'The server becomes completely unreachable and Command activates a paper backup procedure. What is your highest priority?',
                'options' => [
                    'a' => 'Reconstruct every button press from memory at lunch.',
                    'b' => 'Capture the assigned robot, match identity, and only observations the backup process can record reliably.',
                    'c' => 'Watch the whole alliance and estimate everyone\'s totals.',
                    'd' => 'Stop watching matches because digital entry is unavailable.',
                ],
                'correct' => 'b',
                'explanation' => 'Backup scouting is still evidence collection. Preserve identity and defensible observations so later re-entry does not rely on invented precision.',
            ],
            [
                'id' => 'sct13',
                'question' => 'In Tag Scouting, what does a 70% scoring-share estimate mean?',
                'options' => [
                    'a' => 'The robot scored exactly 70 official points.',
                    'b' => 'The observer estimates the robot contributed about 70% of its alliance\'s scoring output for that match.',
                    'c' => 'The robot has a 70% win probability.',
                    'd' => 'The robot completed 70% of its attempted shots.',
                ],
                'correct' => 'b',
                'explanation' => 'Tag scoring share is a relative contribution estimate from 0–100, not a raw point total, success rate, or win probability.',
            ],
            [
                'id' => 'sct14',
                'question' => 'Three Tag scouts independently observe the same robot and enter 60%, 70%, and 80% scoring-share estimates. With Tag analytics currently disabled in AUGUR, what is the correct way to treat those records?',
                'options' => [
                    'a' => 'Keep them as three independent Tag observations and review them together as supporting evidence; do not convert them into Traditional actions or assume AUGUR has automatically averaged them.',
                    'b' => 'Keep only the highest estimate because the most confident observer should win.',
                    'c' => 'Replace all three with their mathematical average in the Traditional scouting record.',
                    'd' => 'Delete two of them because Neptune should have only one observer per robot.',
                ],
                'correct' => 'a',
                'explanation' => 'Tag Scouting preserves independent observations. At present, Tag records are collected for review but are not fed into AUGUR analytics, EPA, predictions, or Traditional action metrics.',
            ],
            [
                'id' => 'sct15',
                'question' => 'Using the team\'s current Tag Scouting training convention, which weight range should a scout use when assigning a strength/evidence weight to a selected tag?',
                'options' => [
                    'a' => '0–100',
                    'b' => '1–5',
                    'c' => '-5–5',
                    'd' => '1–10',
                ],
                'correct' => 'b',
                'explanation' => 'The team training convention uses a 1–5 tag-strength scale. The number describes how strongly the observed match supports that selected tag; it is not a score percentage or a count of matches.',
            ],
            [
                'id' => 'sct16',
                'question' => 'Using the team\'s training convention, what should a Tag weight of 5 mean?',
                'options' => [
                    'a' => 'The behavior was barely demonstrated.',
                    'b' => 'There was some weak evidence.',
                    'c' => 'The behavior was dominant or unmistakable in that match.',
                    'd' => 'The robot has shown the behavior at five different events.',
                ],
                'correct' => 'c',
                'explanation' => 'The training convention is 1 = weak/barely demonstrated through 5 = dominant/unmistakable. It is a consistency rubric for observers, not a count of matches.',
            ],
            [
                'id' => 'sct17',
                'question' => 'Using the team\'s training convention, when is a Tag weight of 1 appropriate?',
                'options' => [
                    'a' => 'The behavior was weak or barely demonstrated.',
                    'b' => 'The behavior was dominant.',
                    'c' => 'The robot won the match.',
                    'd' => 'The observer has only scouted once before.',
                ],
                'correct' => 'a',
                'explanation' => 'Tag weight is about strength of evidence for that observed behavior, not scout seniority, win/loss, or season history.',
            ],
            [
                'id' => 'sct18',
                'question' => 'A robot was known as an Elite Defender at its last event, but in the match you are Tag scouting it never plays defense. Which observation is most defensible?',
                'options' => [
                    'a' => 'Select Elite Defense because historical reputation should carry forward.',
                    'b' => 'Record the current match rather than the reputation: use No Defense for this match when that tag describes the observed behavior, and do not copy Elite Defense from history.',
                    'c' => 'Select Good Defense with weight 3 as a compromise between history and today.',
                    'd' => 'Select Elite Defense and No Defense together so Strategy can decide later.',
                ],
                'correct' => 'b',
                'explanation' => 'Tag Match observations describe what happened in the match being watched. “No Defense” is a current-match observation, not a claim that the robot is incapable of defense at other times.',
            ],
            [
                'id' => 'sct19',
                'question' => 'A robot spends the entire match intentionally defending and repeatedly disrupts top scorers. Which Tag combination is most defensible?',
                'options' => [
                    'a' => 'Good Defense or Elite Defense based on observed effectiveness, with a strength weight that matches the evidence.',
                    'b' => 'Scoring a Lot, because preventing points is equivalent to scoring.',
                    'c' => 'No Defense, because it did not shoot.',
                    'd' => 'Impressive Auton, because defense is impressive.',
                ],
                'correct' => 'a',
                'explanation' => 'Tags should describe the behavior actually observed. Defense quality and weight should reflect effectiveness, not be translated into unrelated scoring/autonomous tags.',
            ],
            [
                'id' => 'sct20',
                'question' => 'A robot makes one unusually fast cycle early but then runs average-speed cycles for the rest of the match. Which use of Fast Cycles is best?',
                'options' => [
                    'a' => 'Automatically give Fast Cycles weight 5 because one cycle was fast.',
                    'b' => 'Use the tag only if the match as a whole provides meaningful evidence; if used, choose a weight reflecting the limited consistency.',
                    'c' => 'Never use Fast Cycles unless you timed every cycle with a stopwatch.',
                    'd' => 'Convert the one cycle into 100% scoring share.',
                ],
                'correct' => 'b',
                'explanation' => 'Tag weights are intended to communicate strength of evidence. One isolated example should not be treated as dominant, match-long behavior.',
            ],
            [
                'id' => 'sct21',
                'question' => 'What is the core difference between Traditional Match Scouting and the Match context of Tag Scouting?',
                'options' => [
                    'a' => 'Traditional records configured action-by-action events for one assigned robot; Tag Match records match-level observations such as scoring share, behavior tags/weights, and concise notes.',
                    'b' => 'Traditional is for admins only; Tag is for scouts only.',
                    'c' => 'Tag replaces robot identity with alliance identity.',
                    'd' => 'Traditional uses TBA while Tag never uses a schedule.',
                ],
                'correct' => 'a',
                'explanation' => 'Traditional and Tag Match collect different evidence. Traditional is detailed action/outcome data for an assigned robot; Tag Match is a match-level observation layer. Tag Scouting also has Pit and Team contexts for quick observations outside a match.',
            ],
            [
                'id' => 'sct22',
                'question' => 'Which task belongs in Tag Scouting\'s Pit or Team context rather than Traditional Match Scouting or Tag Match?',
                'options' => [
                    'a' => 'Building the official qualification schedule.',
                    'b' => 'Capturing a quick team/pit observation with tags or notes and, when useful, a photo or supported video.',
                    'c' => 'Entering every configured match action with Success/Failure for one assigned robot.',
                    'd' => 'Editing Public EPA values.',
                ],
                'correct' => 'b',
                'explanation' => 'Tag Scouting has Match, Pit, and Team contexts. Use Pit or Team for quick contextual observations, tags/notes, and supported media; use Traditional Match Scouting for configured action-by-action Success/Failure data.',
            ],
            [
                'id' => 'sct23',
                'question' => 'Pit scouting says a team can climb. During your assigned match the robot never attempts a climb. What should Traditional Scouting do?',
                'options' => [
                    'a' => 'Record a successful climb because pit scouting says it can.',
                    'b' => 'Record only what occurs in the match; pit capability is context, not proof of an observed action.',
                    'c' => 'Record a failed climb because it chose not to attempt.',
                    'd' => 'Delete the pit answer.',
                ],
                'correct' => 'b',
                'explanation' => 'Pit data often describes capability or claims. Traditional Scouting records observed match behavior and should not manufacture an attempt that never happened.',
            ],
            [
                'id' => 'sct24',
                'question' => 'What is Pre-Scouting primarily meant to provide?',
                'options' => [
                    'a' => 'Research/contact context and reusable season knowledge before the event.',
                    'b' => 'The live match clock.',
                    'c' => 'Official referee decisions.',
                    'd' => 'A replacement for all pit and match observation.',
                ],
                'correct' => 'a',
                'explanation' => 'Pre-Scouting gathers information ahead of competition and can carry compatible season knowledge forward. It is context, not a substitute for current-event observation.',
            ],
            [
                'id' => 'sct25',
                'question' => 'Late in a match, your robot stops moving and appears electrically dead. In Tag Scouting, which action is most defensible?',
                'options' => [
                    'a' => 'Use Disabled / Dead for this match and add brief context if needed, without rewriting its entire season capability.',
                    'b' => 'Tag Mechanical Issues weight 5 for every prior match too.',
                    'c' => 'Set scoring share to 100 because the failure was memorable.',
                    'd' => 'Remove all positive tags from previous matches.',
                ],
                'correct' => 'a',
                'explanation' => 'Tag observations are match-scoped evidence. A current disable can be captured without retroactively changing what the robot did in other matches.',
            ],
            [
                'id' => 'sct26',
                'question' => 'Two Tag observers disagree sharply: one selects Elite Defense weight 5 and the other selects Good Defense weight 2. What should Strategy do rather than choosing one opinion blindly?',
                'options' => [
                    'a' => 'Use the higher weight because a larger number guarantees correctness.',
                    'b' => 'Review both independent Tag observations alongside Traditional data, pit/pre information, and match context; consider sample size and why the observers disagreed.',
                    'c' => 'Use the lower weight because conservative ratings are always safer.',
                    'd' => 'Delete both observations.',
                ],
                'correct' => 'b',
                'explanation' => 'Independent observations can legitimately disagree. Because Tag analytics are not currently feeding AUGUR, Strategy should review the underlying Tag evidence directly and compare it with other sources rather than assuming a software-generated consensus.',
            ],
            [
                'id' => 'sct27',
                'question' => 'You notice the action you just entered is wrong, and the match is moving too fast to troubleshoot. What should you do?',
                'options' => [
                    'a' => 'Create several opposite actions to mathematically cancel it.',
                    'b' => 'Keep tracking the robot, remember/flag the mistake, and notify Command/admin for correction as soon as practical.',
                    'c' => 'Stop scouting the rest of the match.',
                    'd' => 'Refresh until the action disappears.',
                ],
                'correct' => 'b',
                'explanation' => 'Do not sacrifice the rest of the match or fabricate compensating data. Administrative correction is the proper path for a known bad entry.',
            ],
            [
                'id' => 'sct28',
                'question' => 'What should you verify before a Traditional match begins?',
                'options' => [
                    'a' => 'Only your login name.',
                    'b' => 'Event/match, alliance, station, and robot number so you know the screen matches the robot you will physically follow.',
                    'c' => 'The final official score.',
                    'd' => 'The other five scouts\' passwords.',
                ],
                'correct' => 'b',
                'explanation' => 'Most catastrophic scouting errors begin with wrong identity. A short pre-match identity check protects the entire run.',
            ],
            [
                'id' => 'sct29',
                'question' => 'Which dataset is better: 92% complete data with a clearly documented gap, or 100% complete-looking data that includes guessed actions?',
                'options' => [
                    'a' => 'The 100% dataset, because models require every cell.',
                    'b' => 'The honest 92% dataset, because Strategy can account for missingness but cannot reliably detect invented observations.',
                    'c' => 'They are equally trustworthy.',
                    'd' => 'Neither can be used for analytics.',
                ],
                'correct' => 'b',
                'explanation' => 'Data quality is more important than cosmetic completeness. Explicit missing data can be discounted; fabricated data can mislead without warning.',
            ],
            [
                'id' => 'sct30',
                'question' => 'You are asked to cover two robots simultaneously because another scout is missing. What should you do if the match is too fast to observe both reliably?',
                'options' => [
                    'a' => 'Alternate randomly and fill the missing actions from the scoreboard.',
                    'b' => 'Follow the coverage plan Command gives you, prioritize the designated robot(s), and leave unavoidable gaps explicit rather than fabricate details.',
                    'c' => 'Copy another scout\'s actions and change the team number.',
                    'd' => 'Estimate both robots\' actions after the match from memory.',
                ],
                'correct' => 'b',
                'explanation' => 'A known coverage gap is preferable to two unreliable robot histories. Command should decide priorities; the scout should not manufacture completeness.',
            ],
            [
                'id' => 'sct31',
                'question' => 'A Tag scout selects Hard to Defend. What should that mean in a useful observation?',
                'options' => [
                    'a' => 'The robot\'s bumper color is difficult to see.',
                    'b' => 'The robot\'s observed offense continued effectively despite defensive pressure or it was unusually difficult for defenders to disrupt.',
                    'c' => 'The robot played strong defense.',
                    'd' => 'The robot had a high pit-reported hopper size.',
                ],
                'correct' => 'b',
                'explanation' => 'Hard to Defend describes resistance to opposing defense, not the robot\'s own defensive skill or unrelated pit capability.',
            ],
            [
                'id' => 'sct32',
                'question' => 'A robot plays strong defense but receives several penalties while doing so. Which Tag approach preserves both facts?',
                'options' => [
                    'a' => 'Choose only Elite Defense because positive and negative tags cannot coexist.',
                    'b' => 'Tag the defensive quality that was observed and also Penalty Risk when the match supports it.',
                    'c' => 'Choose Mechanical Issues instead.',
                    'd' => 'Set scoring share to zero and use no tags.',
                ],
                'correct' => 'b',
                'explanation' => 'Tags can capture multiple dimensions of one performance. Strong defense and penalty risk are not mutually exclusive and both may matter to Strategy.',
            ],
            [
                'id' => 'sct33',
                'question' => 'Why should a Tag scout add a short note when the available tags do not explain an unusual event?',
                'options' => [
                    'a' => 'To replace the selected tags entirely.',
                    'b' => 'To preserve concise context that Strategy cannot infer from a generic tag alone, while keeping the structured observation intact.',
                    'c' => 'To copy the official play-by-play.',
                    'd' => 'Because every Tag observation requires a paragraph.',
                ],
                'correct' => 'b',
                'explanation' => 'Notes are useful when structured tags lack necessary context. They should clarify the observation, not become an unstructured substitute for the whole workflow.',
            ],
            [
                'id' => 'sct34',
                'question' => 'During one match, a robot repeatedly executes the same scoring routine cleanly with little variation, but you have no earlier Tag observations for it at the event. Can “Consistent” be a defensible Tag?',
                'options' => [
                    'a' => 'Yes—if you mean consistent execution within the match you actually observed and weight it according to that evidence; do not turn it into an unsupported season-long claim.',
                    'b' => 'No—Consistent can only be selected after five different matches.',
                    'c' => 'Yes, and it automatically raises the robot\'s Public EPA.',
                    'd' => 'No—consistency can only be recorded in formal Pit Scouting.',
                ],
                'correct' => 'a',
                'explanation' => 'Tag Match observations are match-scoped. “Consistent” can describe repeated, steady execution within that match. The mistake would be treating one match-level tag as proof of season-long reliability.',
            ],
        ],
    ],
];
