<?php
declare(strict_types=1);
require_once dirname(__DIR__,4).'/neptune_secure/bootstrap.php';
$u=require_role(['owner','admin']);require_once __DIR__.'/_training.php';neptune_training_ensure_schema($pdo);
$org=(int)$u['organization_id'];$courses=neptune_training_courses();
if(isset($_GET['export'])&&$_GET['export']==='csv'){
  $s=$pdo->prepare("SELECT display_name_snapshot,username_snapshot,role_snapshot,course_code,attempt_number,score_percent,passed,correct_count,question_count,duration_seconds,completed_at FROM training_attempts WHERE organization_id=? AND status='completed' ORDER BY completed_at DESC,id DESC");$s->execute([$org]);
  header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="neptune-training-records.csv"');$out=fopen('php://output','w');fputcsv($out,['Name','Username','Role','Course','Attempt','Grade %','Passed','Correct','Questions','Duration seconds','Completed UTC']);foreach($s->fetchAll() as $r)fputcsv($out,[$r['display_name_snapshot'],$r['username_snapshot'],$r['role_snapshot'],$r['course_code'],$r['attempt_number'],$r['score_percent'],(int)$r['passed']===1?'Yes':'No',$r['correct_count'],$r['question_count'],$r['duration_seconds'],$r['completed_at']]);fclose($out);exit;
}
$s=$pdo->prepare("SELECT u.id,u.display_name,u.username,u.role,u.active,
 (SELECT COUNT(*) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='admin' AND a.status='completed') admin_attempts,
 (SELECT MAX(score_percent) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='admin' AND a.status='completed') admin_best,
 (SELECT MAX(passed) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='admin' AND a.status='completed') admin_passed,
 (SELECT COUNT(*) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='scouter' AND a.status='completed') scout_attempts,
 (SELECT MAX(score_percent) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='scouter' AND a.status='completed') scout_best,
 (SELECT MAX(passed) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.course_code='scouter' AND a.status='completed') scout_passed,
 (SELECT MAX(completed_at) FROM training_attempts a WHERE a.organization_id=u.organization_id AND a.user_id=u.id AND a.status='completed') last_training
 FROM users u WHERE u.organization_id=? ORDER BY u.active DESC,u.display_name,u.username");$s->execute([$org]);$users=$s->fetchAll();
$s=$pdo->prepare("SELECT id,display_name_snapshot,username_snapshot,role_snapshot,course_code,attempt_number,score_percent,passed,correct_count,question_count,duration_seconds,completed_at FROM training_attempts WHERE organization_id=? AND status='completed' ORDER BY completed_at DESC,id DESC LIMIT 100");$s->execute([$org]);$attempts=$s->fetchAll();
$pageTitle='Training Records';$moduleName='NEPTUNE';$bodyClass='training-records-page';include dirname(__DIR__,2).'/partials_header.php';
$trainingActive='records';
?>
<style>.training-pass{color:var(--good);font-weight:900}.training-fail{color:var(--bad);font-weight:900}.training-na{color:var(--muted)}.training-records-page .table td{vertical-align:middle}.training-grade{font-weight:950;white-space:nowrap}.training-cell small{display:block;color:var(--muted);margin-top:2px}</style>
<div class="ntp-hub">
<section class="neptune-page-hero"><div class="neptune-hero-kicker"><i class="fa-solid fa-chart-column"></i> NEPTUNE · TRAINING ADMINISTRATION</div><h1>Training Records</h1><p>Organization-scoped CBT completion and grades. Every submitted attempt is retained; the matrix shows each user's best result.</p><div class="toolbar ntp-hero-actions"><a class="btn secondary" href="<?=e(base_url('help/training/'))?>"><i class="fa-solid fa-arrow-left"></i> Training Center</a><a class="btn secondary" href="?export=csv"><i class="fa-solid fa-file-csv"></i> Export CSV</a></div></section>
<?php include dirname(__DIR__).'/_training_nav.php'; ?>
</div>
<section class="card"><h2>Certification matrix</h2><div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Role</th><th>Admin CBT</th><th>Scouter CBT</th><th>Last training</th></tr></thead><tbody><?php foreach($users as $r):?><tr><td><b><?=e($r['display_name']?:$r['username'])?></b><small class="muted"><?=e($r['username'])?><?=$r['active']?'':' · inactive'?></small></td><td><?=e(ucfirst((string)$r['role']))?></td><td class="training-cell"><?php if((int)$r['admin_attempts']<1):?><span class="training-na">Not taken</span><?php else:?><span class="training-grade"><?=e(neptune_training_score_label($r['admin_best']))?></span> <span class="<?=((int)$r['admin_passed']===1?'training-pass':'training-fail')?>"><?=((int)$r['admin_passed']===1?'PASS':'NOT PASS')?></span><small><?=e($r['admin_attempts'])?> attempt<?=((int)$r['admin_attempts']===1?'':'s')?></small><?php endif;?></td><td class="training-cell"><?php if((int)$r['scout_attempts']<1):?><span class="training-na">Not taken</span><?php else:?><span class="training-grade"><?=e(neptune_training_score_label($r['scout_best']))?></span> <span class="<?=((int)$r['scout_passed']===1?'training-pass':'training-fail')?>"><?=((int)$r['scout_passed']===1?'PASS':'NOT PASS')?></span><small><?=e($r['scout_attempts'])?> attempt<?=((int)$r['scout_attempts']===1?'':'s')?></small><?php endif;?></td><td><?=e($r['last_training']?:'—')?><?=$r['last_training']?' UTC':''?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card" style="margin-top:16px"><h2>Recent graded attempts</h2><div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Course</th><th>Attempt</th><th>Grade</th><th>Result</th><th>Correct</th><th>Time</th><th>Completed</th><th></th></tr></thead><tbody><?php foreach($attempts as $r):$c=$courses[$r['course_code']]??null;?><tr><td><b><?=e($r['display_name_snapshot'])?></b><small class="muted"><?=e($r['username_snapshot'])?> · <?=e($r['role_snapshot'])?></small></td><td><?=e($c['short_title']??$r['course_code'])?></td><td>#<?=e($r['attempt_number'])?></td><td class="training-grade"><?=e(neptune_training_score_label($r['score_percent']))?></td><td class="<?=((int)$r['passed']===1?'training-pass':'training-fail')?>"><?=((int)$r['passed']===1?'PASS':'NOT PASS')?></td><td><?=e($r['correct_count'])?> / <?=e($r['question_count'])?></td><td><?=e(neptune_training_duration((int)$r['duration_seconds']))?></td><td><?=e($r['completed_at'])?> UTC</td><td><a class="btn secondary" href="<?=e(base_url('help/training/attempt.php?id='.(int)$r['id']))?>">Review</a></td></tr><?php endforeach;?></tbody></table></div></section>
<?php include dirname(__DIR__,2).'/partials_footer.php';?>
