<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/neptune_secure/bootstrap.php';
require_once dirname(__DIR__).'/analytics/_augur_depa.php';
header('Content-Type: application/json; charset=utf-8');header('Access-Control-Allow-Origin: *');header('Cache-Control: public, max-age=300');
if($_SERVER['REQUEST_METHOD']!=='GET'){http_response_code(405);header('Allow: GET');echo json_encode(['error'=>'GET only']);exit;}
if(!augur_depa_tables_ready($pdo)){http_response_code(503);echo json_encode(['error'=>'Neptune D-EPA archive is not installed']);exit;}
$seasonPublicColumns=false;$defenseAttemptColumns=false;
try{
    $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='augur_depa_public_season_ratings' AND COLUMN_NAME IN ('public_depa','public_matches')");
    $q->execute();
    $seasonPublicColumns=((int)$q->fetchColumn()===2);
    $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='augur_depa_public_event_ratings' AND COLUMN_NAME IN ('defense_failures','defense_attempts')");$q->execute();$defenseAttemptColumns=((int)$q->fetchColumn()===2);
}catch(Throwable $e){}
$year=(int)($_GET['year']??0);$event=trim((string)($_GET['event']??''));$team=(int)($_GET['team']??0);$eventsOnly=(string)($_GET['events']??'')==='1';
$meta=['product'=>'Neptune D-EPA','model_version'=>AUGUR_DEPA_MODEL_VERSION,'higher_is_better'=>true,'network_scope'=>'All Neptune organizations','depa_definition'=>'All-match D-EPA = projected opponent score minus actual modeled opponent score, averaged across all qualification matches; inference only, not proof of defense','neptune_depa_definition'=>'Neptune D-EPA = the same match D-EPA averaged only across canonical Verified defense matches','dedupe_key'=>'TBA match key + FRC team number','defense_action_merge'=>'one highest-coverage organization observation per canonical match/team; cross-organization actions are never summed','verified_rule'=>'2+ total defense attempts (success or failure) within one organization observation OR a Spot great/weak defense tag','effectiveness_rule'=>'successes and failures identify action effectiveness; match D-EPA supplies the scoring impact','privacy'=>'Public output contains no organization identities, scout identities, IP addresses, notes, or raw private scouting rows.'];
try{
    if($eventsOnly){if($year<=0)$year=(int)date('Y');$q=$pdo->prepare("SELECT e.tba_event_key,e.season_year,e.name,e.start_date,e.end_date,COUNT(r.frc_team_number) depa_rated_teams,COUNT(CASE WHEN r.observed_matches>0 THEN 1 END) observed_team_rows,COUNT(CASE WHEN r.neptune_depa IS NOT NULL THEN 1 END) neptune_rated_teams FROM augur_epa_archive_events e LEFT JOIN augur_depa_public_event_ratings r ON r.tba_event_key=e.tba_event_key WHERE e.season_year=? GROUP BY e.tba_event_key,e.season_year,e.name,e.start_date,e.end_date ORDER BY COALESCE(e.start_date,e.end_date),e.name");$q->execute([$year]);$data=$q->fetchAll();echo json_encode(['meta'=>$meta,'year'=>$year,'events'=>$data],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
    if($event!==''){$attemptFields=$defenseAttemptColumns?'defense_failures,defense_attempts':'0 AS defense_failures,defense_actions AS defense_attempts';$sql="SELECT tba_event_key,season_year,frc_team_number,macro_depa AS depa,matches_played,neptune_depa,verified_defense_matches,possible_defense_matches,observed_matches,defense_actions,{$attemptFields},contributing_orgs,confidence_score,confidence_label,validation_label,model_version,calculated_at FROM augur_depa_public_event_ratings WHERE tba_event_key=?";$p=[$event];if($team>0){$sql.=' AND frc_team_number=?';$p[]=$team;}$sql.=' ORDER BY neptune_depa IS NULL,neptune_depa DESC,depa DESC,confidence_score DESC,frc_team_number';$q=$pdo->prepare($sql);$q->execute($p);echo json_encode(['meta'=>$meta,'event'=>$event,'ratings'=>$q->fetchAll()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
    if($year<=0)$year=(int)date('Y');$sql=$seasonPublicColumns
    ?($defenseAttemptColumns?"SELECT season_year,frc_team_number,public_depa AS depa,public_matches,neptune_depa,verified_defense_matches,possible_defense_matches,observed_matches,defense_actions,defense_failures,defense_attempts,contributing_orgs,events_observed,rated_events,confidence_score,confidence_label,validation_label,last_event_key,model_version,calculated_at FROM augur_depa_public_season_ratings WHERE season_year=?":"SELECT season_year,frc_team_number,public_depa AS depa,public_matches,neptune_depa,verified_defense_matches,possible_defense_matches,observed_matches,defense_actions,0 AS defense_failures,defense_actions AS defense_attempts,contributing_orgs,events_observed,rated_events,confidence_score,confidence_label,validation_label,last_event_key,model_version,calculated_at FROM augur_depa_public_season_ratings WHERE season_year=?")
    :"SELECT season_year,frc_team_number,NULL AS depa,0 AS public_matches,neptune_depa,verified_defense_matches,possible_defense_matches,observed_matches,defense_actions,0 AS defense_failures,defense_actions AS defense_attempts,contributing_orgs,events_observed,rated_events,confidence_score,confidence_label,validation_label,last_event_key,model_version,calculated_at FROM augur_depa_public_season_ratings WHERE season_year=?";$p=[$year];if($team>0){$sql.=' AND frc_team_number=?';$p[]=$team;}$sql.=' ORDER BY neptune_depa IS NULL,neptune_depa DESC,depa DESC,confidence_score DESC,frc_team_number';$q=$pdo->prepare($sql);$q->execute($p);echo json_encode(['meta'=>$meta,'year'=>$year,'ratings'=>$q->fetchAll()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
}catch(Throwable $e){http_response_code(500);echo json_encode(['error'=>'Unable to read Neptune D-EPA archive']);}
