<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/neptune_secure/bootstrap.php';
require_once dirname(__DIR__).'/analytics/_augur_depa.php';
$u=require_role(['owner']);
$platformOrgId=(int)($config['app']['platform_organization_id']??1);if((int)($u['organization_id']??0)!==$platformOrgId){http_response_code(403);exit('Platform owner access required.');}
$pageTitle='AUGUR Neptune D-EPA Network';$moduleName='AUGUR';
const NDB_JOB_DIR='/tmp/neptune-augur-depa-beta';const NDB_JOB_FILE=NDB_JOB_DIR.'/job.json';
function ndb_e(string $v): string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}function ndb_flash(string $type,string $msg): void{$_SESSION['ndb_flash']=[$type,$msg];}function ndb_take_flash(): ?array{$x=$_SESSION['ndb_flash']??null;unset($_SESSION['ndb_flash']);return is_array($x)?$x:null;}function ndb_job_read(): array{if(!is_file(NDB_JOB_FILE))return[];$j=json_decode((string)@file_get_contents(NDB_JOB_FILE),true);return is_array($j)?$j:[];}function ndb_job_running(array $job): bool{$pid=(int)($job['pid']??0);if($pid<=0||!is_dir('/proc/'.$pid))return false;$cmd=@file_get_contents('/proc/'.$pid.'/cmdline');return $cmd===false||str_contains(str_replace("\0",' ',$cmd),'augur-depa-backfill-cli.php');}function ndb_tail(string $path,int $n=80): string{if(!is_file($path))return'';$x=@file($path,FILE_IGNORE_NEW_LINES);return is_array($x)?implode("\n",array_slice($x,-$n)):'';}function ndb_exec_available(): bool{$disabled=array_map('trim',explode(',',(string)ini_get('disable_functions')));return function_exists('exec')&&!in_array('exec',$disabled,true);}
function ndb_launch(int $start,int $end): array{if(!ndb_exec_available())throw new RuntimeException('PHP exec() is disabled; run the CLI command shown below instead.');$existing=ndb_job_read();if($existing&&ndb_job_running($existing))throw new RuntimeException('A D-EPA rebuild is already running.');$php=is_executable('/usr/bin/php')?'/usr/bin/php':PHP_BINARY;$script=__DIR__.'/augur-depa-backfill-cli.php';if(!is_file($script))throw new RuntimeException('D-EPA CLI script is missing.');if(!is_dir(NDB_JOB_DIR)&&!mkdir(NDB_JOB_DIR,0770,true)&&!is_dir(NDB_JOB_DIR))throw new RuntimeException('Could not create D-EPA job directory.');$log=NDB_JOB_DIR.'/depa-'.date('Ymd-His').'.log';$cmd='nohup '.escapeshellarg($php).' '.escapeshellarg($script).' '.escapeshellarg((string)$start).' '.escapeshellarg((string)$end).' >> '.escapeshellarg($log).' 2>&1 < /dev/null & echo $!';$o=[];$code=0;exec($cmd,$o,$code);$pid=(int)trim((string)($o[0]??'0'));if($code!==0||$pid<=0)throw new RuntimeException('Could not start the D-EPA background rebuild.');$job=['pid'=>$pid,'start_year'=>$start,'end_year'=>$end,'log'=>$log,'started_at'=>date(DATE_ATOM)];file_put_contents(NDB_JOB_FILE,json_encode($job,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);return $job;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$op=(string)($_POST['op']??'');try{if($op==='install'){augur_depa_install_tables($pdo);ndb_flash('good','Neptune D-EPA network tables are installed.');}elseif($op==='rebuild'){$start=(int)($_POST['start_year']??date('Y'));$end=(int)($_POST['end_year']??$start);$max=(int)date('Y')+1;if($start<1992||$end<1992||$start>$max||$end>$max)throw new RuntimeException('Choose a valid FRC season range.');if($start>$end)[$start,$end]=[$end,$start];augur_depa_install_tables($pdo);ndb_launch($start,$end);ndb_flash('good',"Neptune-wide D-EPA rebuild started for {$start}–{$end}.");}}catch(Throwable $e){ndb_flash('bad',$e->getMessage());}header('Location: '.base_url('admin/augur-depa-beta.php'));exit;}
$ready=augur_depa_tables_ready($pdo);
$schemaCurrent=false;
try{
    $q=$pdo->prepare("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='augur_depa_public_season_ratings' AND COLUMN_NAME IN ('public_depa','public_matches','defense_failures','defense_attempts')");
    $q->execute();
    $schemaCurrent=((int)$q->fetchColumn()===4);
}catch(Throwable $e){}
$job=ndb_job_read();$running=$job&&ndb_job_running($job);$log=$job?ndb_tail((string)($job['log']??'')):'';$flash=ndb_take_flash();$current=(int)date('Y');
$stats=['samples'=>0,'network'=>0,'event'=>0,'season'=>0,'orgs'=>0,'latest'=>null];if($ready){try{$stats['samples']=(int)$pdo->query('SELECT COUNT(*) FROM augur_depa_match_samples')->fetchColumn();}catch(Throwable $e){}try{$stats['network']=(int)$pdo->query('SELECT COUNT(*) FROM augur_depa_network_match_evidence')->fetchColumn();}catch(Throwable $e){}try{$stats['event']=(int)$pdo->query('SELECT COUNT(*) FROM augur_depa_public_event_ratings WHERE observed_matches>0')->fetchColumn();}catch(Throwable $e){}try{$stats['season']=(int)$pdo->query('SELECT COUNT(*) FROM augur_depa_public_season_ratings')->fetchColumn();}catch(Throwable $e){}try{$stats['orgs']=(int)$pdo->query("SELECT COUNT(DISTINCT sa.organization_id) FROM scouting_actions sa JOIN events e ON e.id=sa.event_id WHERE sa.deleted_at IS NULL AND e.tba_event_key IS NOT NULL AND e.tba_event_key<>''")->fetchColumn();}catch(Throwable $e){}try{$stats['latest']=$pdo->query('SELECT MAX(calculated_at) FROM augur_depa_public_season_ratings')->fetchColumn()?:null;}catch(Throwable $e){}}
include dirname(__DIR__).'/partials_header.php';?>
<style>.depa-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.depa-stat{padding:16px;border:1px solid var(--border);border-radius:16px;background:var(--panel)}.depa-stat b{display:block;font-size:1.55rem}.depa-actions{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.depa-actions label{min-width:140px}.depa-log{max-height:360px;overflow:auto;white-space:pre-wrap;background:#05080b;color:#dce8ef;padding:14px;border-radius:14px;font-size:.84rem}.depa-pill{display:inline-flex;gap:6px;align-items:center;padding:4px 9px;border-radius:999px;background:#6d4cff22;color:#9f8cff;border:1px solid #6d4cff55;font-weight:800;font-size:.75rem}@media(max-width:800px){.depa-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.depa-grid{grid-template-columns:1fr}.depa-actions>*{width:100%}}</style>
<section class="module-page"><header class="module-page-header"><div><div class="module-code">AUGUR · PUBLIC NETWORK</div><h1>Neptune D-EPA Data Lab <span class="depa-pill">v6.2</span></h1><p>Build Neptune-wide defensive ratings from every organization's scouting while publishing only deduplicated, organization-agnostic results.</p></div><a class="btn secondary" href="<?=e(base_url('analytics/depa-beta.php'))?>"><i class="fa-solid fa-chart-column"></i> View Public Neptune D-EPA</a></header>
<?php if($flash):?><div class="notice <?=$flash[0]==='good'?'good':'bad'?>"><b><?=ndb_e($flash[1])?></b></div><?php endif;?>
<div class="card"><h2>Network model boundary</h2><p><b>Neptune D-EPA</b> is the mean Raw D-EPA from canonical <b>Verified</b> defense matches. Raw D-EPA remains projected opponent score from pre-match Public EPA minus actual modeled opponent score.</p><p class="muted">Every Neptune organization can contribute. Overlapping scouting is collapsed by <b>TBA match key + FRC team</b>. Each organization first gets one observation; cross-org action evidence uses the <b>single highest-coverage organization observation, never a summed duplicate</b>. Successes and failures are both retained. A match is Verified if any observing organization independently records 2+ defense attempts (success or failure), or a Spot defense tag. Public tables store contributor counts, not organization identities or raw private scouting.</p></div>
<div class="card"><h2>Install / upgrade D-EPA tables</h2><p>Safe to run again. This creates missing tables and adds columns required by the current D-EPA pages without changing Match Scouting data.</p><?php if(!$schemaCurrent):?><div class="notice bad" style="margin-bottom:12px"><b>Database upgrade required.</b> The current code expects the all-match D-EPA and defense success/failure/attempt columns.</div><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="op" value="install"><button><i class="fa-solid fa-database"></i> Install / Upgrade D-EPA Tables</button></form></div>
<?php if(!$ready):?><div class="notice bad"><b>D-EPA tables are not installed yet.</b> Use the Install / Upgrade button above.</div><?php else:?>
<div class="depa-grid"><div class="depa-stat"><span class="muted">Public match samples</span><b><?=number_format($stats['samples'])?></b></div><div class="depa-stat"><span class="muted">Canonical observations</span><b><?=number_format($stats['network'])?></b></div><div class="depa-stat"><span class="muted">Event team rows</span><b><?=number_format($stats['event'])?></b></div><div class="depa-stat"><span class="muted">Season team rows</span><b><?=number_format($stats['season'])?></b></div><div class="depa-stat"><span class="muted">Contributing orgs</span><b><?=number_format($stats['orgs'])?></b><small class="muted"><?=ndb_e((string)($stats['latest']??'Not rebuilt yet'))?></small></div></div>
<div class="card"><h2>Backfill / rebuild</h2><p>Rebuilds Public EPA-based Raw D-EPA, reads scouting from <b>all organizations</b>, deduplicates overlapping robot/match observations, and regenerates public event and season Neptune D-EPA ratings.</p><form method="post" class="depa-actions"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="op" value="rebuild"><label>Start season<input type="number" name="start_year" min="1992" max="<?=$current+1?>" value="<?=$current?>"></label><label>End season<input type="number" name="end_year" min="1992" max="<?=$current+1?>" value="<?=$current?>"></label><button <?=$running?'disabled':''?>><i class="fa-solid fa-rotate"></i> <?=$running?'Rebuild Running…':'Start Neptune D-EPA Rebuild'?></button></form><p class="muted">Prerequisite: the Public EPA archive must already be populated for the season. A Neptune organization only contributes to a robot/match when it actually recorded scouting actions or a Spot observation for that robot in that TBA match.</p></div>
<?php if($job):?><div class="card"><h2>Latest rebuild <?=$running?'<span class="depa-pill">RUNNING</span>':''?></h2><p class="muted">PID <?=ndb_e((string)($job['pid']??''))?> · <?=ndb_e((string)($job['start_year']??''))?>–<?=ndb_e((string)($job['end_year']??''))?> · <?=ndb_e((string)($job['started_at']??''))?></p><pre class="depa-log"><?=ndb_e($log!==''?$log:'Waiting for output…')?></pre><?php if($running):?><script>setTimeout(()=>location.reload(),4000)</script><?php endif;?></div><?php endif;?>
<div class="card"><h2>CLI alternative</h2><pre>cd /var/www/neptune/public_html/Neptune
sudo -u www-data php admin/augur-depa-backfill-cli.php <?=$current?> <?=$current?></pre></div><?php endif;?></section><?php include dirname(__DIR__).'/partials_footer.php';?>
