<?php
require_once dirname(__DIR__,3).'/neptune_secure/bootstrap.php';
require_once dirname(__DIR__,3).'/neptune_secure/themes.php';
$u=require_role(['owner','admin']);$org=(int)$u['organization_id'];$userId=(int)$u['id'];neptune_theme_ensure_schema($pdo);
$pageTitle='Interface Styling';$moduleName='SATURN';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();
  try{
    $action=(string)($_POST['action']??'');
    if($action==='apply_builtin'){$key=neptune_theme_slugify((string)($_POST['theme_key']??''));$t=neptune_theme_builtin($key);if(!$t)throw new RuntimeException('Theme not found.');neptune_theme_set_active($pdo,$org,$userId,'builtin',$key);if(function_exists('neptune_auth_audit'))neptune_auth_audit($pdo,$org,$userId,'organization_theme_applied','organization',(string)$org,['type'=>'builtin','key'=>$key]);header('Location: '.base_url('admin/styling.php?saved=1'));exit;}
    if($action==='apply_custom'){$id=(int)($_POST['theme_id']??0);if(!neptune_theme_custom($pdo,$org,$id))throw new RuntimeException('Theme not found.');neptune_theme_set_active($pdo,$org,$userId,'custom',(string)$id);if(function_exists('neptune_auth_audit'))neptune_auth_audit($pdo,$org,$userId,'organization_theme_applied','organization',(string)$org,['type'=>'custom','theme_id'=>$id]);header('Location: '.base_url('admin/styling.php?saved=1'));exit;}
    if($action==='save_theme'){$id=(int)($_POST['theme_id']??0);$palette=['dark'=>is_array($_POST['dark']??null)?$_POST['dark']:[],'light'=>is_array($_POST['light']??null)?$_POST['light']:[]];$saved=neptune_theme_save($pdo,$org,$userId,(string)($_POST['theme_name']??''),$palette,$id);if(!empty($_POST['apply_after_save']))neptune_theme_set_active($pdo,$org,$userId,'custom',(string)$saved);if(function_exists('neptune_auth_audit'))neptune_auth_audit($pdo,$org,$userId,$id?'organization_theme_updated':'organization_theme_created','organization_theme',(string)$saved,[]);header('Location: '.base_url('admin/styling.php?theme_saved=1'));exit;}
    if($action==='delete_theme'){$id=(int)($_POST['theme_id']??0);neptune_theme_delete($pdo,$org,$id);if(function_exists('neptune_auth_audit'))neptune_auth_audit($pdo,$org,$userId,'organization_theme_deleted','organization_theme',(string)$id,[]);header('Location: '.base_url('admin/styling.php?deleted=1'));exit;}
    throw new RuntimeException('Unknown styling action.');
  }catch(Throwable $e){$error=$e->getMessage();}
}
$builtins=neptune_theme_builtins();$customThemes=neptune_theme_custom_list($pdo,$org);$active=neptune_theme_active($pdo,$org);$catalog=neptune_theme_catalog();
$darkGroups=[
 'Foundation'=>['bg'=>'Page background','bg2'=>'Background 2','panel'=>'Panel','panel2'=>'Panel 2','line'=>'Borders','text'=>'Text','muted'=>'Muted text','bg-glow'=>'Background glow','shadow'=>'Shadow'],
 'Brand & Status'=>['c1-blue'=>'Primary','accent'=>'Accent','c1-red'=>'Competition red','c1-green'=>'Competition green','good'=>'Success','bad'=>'Error','warn'=>'Warning','ready'=>'Ready','solid-text'=>'Solid text'],
 'Game Actions'=>['game-primary'=>'Primary scoring','game-secondary'=>'Secondary scoring','game-intake'=>'Intake','game-defense'=>'Defense','game-coop'=>'Co-op','game-endgame'=>'Endgame','game-special'=>'Special','game-utility'=>'Utility'],
 'Subsystems'=>['module-trident'=>'TRIDENT','module-augur'=>'AUGUR','module-saturn'=>'SATURN','module-vulcan'=>'VULCAN','module-system'=>'MERCURY','module-org'=>'Organization','module-ops'=>'Operations'],
 'Access'=>['access-strategy'=>'Strategy+','access-admin'=>'Admin+','access-owner'=>'Platform owner'],
];
$lightFields=['bg'=>'Page background','bg2'=>'Background 2','panel'=>'Panel','panel2'=>'Panel 2','line'=>'Borders','text'=>'Text','muted'=>'Muted text','c1-blue'=>'Primary','solid-text'=>'Solid text','accent'=>'Accent','good'=>'Success','bad'=>'Error','warn'=>'Warning','bg-glow'=>'Background glow','shadow'=>'Shadow'];
$builtinsJs=[];foreach($builtins as $k=>$t)$builtinsJs[$k]=['name'=>$t['name'],'palette'=>$t['palette']];$customJs=[];foreach($customThemes as $t)$customJs[(string)$t['id']]=['id'=>(int)$t['id'],'name'=>$t['name'],'palette'=>$t['palette']];
include dirname(__DIR__).'/partials_header.php';
?>
<style>
.style-page{display:grid;gap:18px}.style-head{display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap}.style-head h2{margin:0}.style-head p{margin:4px 0 0;color:var(--muted)}
.theme-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:12px}.theme-card{position:relative;display:grid;gap:10px;padding:15px;border:1px solid var(--line);border-radius:16px;background:var(--panel);box-shadow:0 12px 26px var(--shadow);transition:border-color .16s ease,transform .16s ease,box-shadow .16s ease}.theme-card[data-apply-form]{cursor:pointer}.theme-card[data-apply-form]:hover{border-color:color-mix(in srgb,var(--accent) 55%,var(--line));transform:translateY(-1px);box-shadow:0 15px 30px var(--shadow)}.theme-card[data-apply-form]:focus-visible{outline:3px solid color-mix(in srgb,var(--accent) 38%,transparent);outline-offset:2px}.theme-card.active{cursor:default;border-color:var(--accent);box-shadow:0 0 0 2px color-mix(in srgb,var(--accent) 18%,transparent),0 12px 26px var(--shadow)}.theme-card h3{margin:0}.theme-card p{margin:0;color:var(--muted);font-size:.8rem}.theme-top{display:flex;justify-content:space-between;gap:8px}.theme-swatches{height:28px;display:grid;grid-template-columns:repeat(6,1fr);border-radius:9px;overflow:hidden;border:1px solid var(--line)}.theme-actions{display:flex;justify-content:flex-end;gap:7px;flex-wrap:wrap}.theme-actions form{margin:0}.theme-icon-action{width:38px;height:38px;display:grid;place-items:center;padding:0!important;border-radius:10px}.theme-icon-action i{margin:0}.theme-kind{font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);font-weight:850}
.theme-editor{width:min(1100px,calc(100vw - 24px));height:min(90vh,900px);padding:0;border:1px solid var(--line);border-radius:20px;background:var(--panel);color:var(--text);box-shadow:0 30px 100px rgba(0,0,0,.55)}.theme-editor::backdrop{background:rgba(3,7,12,.72);backdrop-filter:blur(6px)}.editor-shell{height:100%;display:grid;grid-template-rows:auto 1fr auto}.editor-head,.editor-foot{padding:16px 18px;background:var(--panel);display:flex;justify-content:space-between;gap:12px;align-items:center}.editor-head{border-bottom:1px solid var(--line)}.editor-foot{border-top:1px solid var(--line)}.editor-head h2{margin:0}.editor-body{overflow:auto;padding:16px 18px;background:var(--bg)}.editor-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(270px,.5fr);gap:16px}.editor-fields{display:grid;gap:12px}.editor-section{padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel)}.editor-section h3{margin:0 0 10px}.palette-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.palette-field{display:grid;grid-template-columns:38px minmax(0,1fr);gap:7px;align-items:end}.palette-field label{grid-column:1/-1;margin:0;color:var(--muted);font-size:.72rem;font-weight:800}.palette-field input[type=color]{width:38px;height:38px;padding:2px}.palette-field input[type=text]{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.preview{position:sticky;top:0;display:grid;gap:10px}.preview-box{padding:14px;border:1px solid var(--pv-line);border-radius:14px;background:linear-gradient(180deg,var(--pv-bg),var(--pv-bg2));color:var(--pv-text)}.preview-card{padding:12px;border:1px solid var(--pv-line);border-radius:10px;background:var(--pv-panel)}.preview-muted{color:var(--pv-muted);font-size:.78rem}.preview-row{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.preview-btn{padding:7px 9px;border-radius:7px;background:var(--pv-primary);color:var(--pv-solid);font-size:.74rem;font-weight:850}.preview-chip{padding:5px 7px;border-radius:999px;border:1px solid var(--pv-line);background:var(--pv-panel2);font-size:.68rem}.preview-swatches{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:10px}.preview-swatches span{height:20px;border-radius:5px}.editor-meta{display:grid;grid-template-columns:minmax(0,1fr) 220px;gap:10px;margin-bottom:14px}.editor-foot-right{display:flex;gap:8px;flex-wrap:wrap}.theme-delete-zone{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.theme-delete-confirm:not([hidden]){display:flex;align-items:center;gap:8px;flex-wrap:wrap}.theme-delete-confirm span{font-size:.8rem;color:var(--muted);font-weight:750}.theme-delete-confirm .danger{white-space:nowrap}
@media(max-width:850px){.editor-layout{grid-template-columns:1fr}.preview{position:static}}@media(max-width:620px){.palette-grid{grid-template-columns:1fr}.editor-meta{grid-template-columns:1fr}.theme-editor{width:calc(100vw - 10px);height:94vh}}
</style>
<section class="module-page style-page">
<section class="neptune-page-hero"><div><div class="neptune-hero-kicker"><i class="fa-solid fa-palette"></i> SATURN · ORGANIZATION</div><h1>Interface Styling</h1><p>Create and manage themes for <b><?=e($u['organization_name'])?></b>. Theme changes are organization-scoped and require Admin or Owner access.</p><div class="neptune-hero-pills"><span class="neptune-hero-pill"><i class="fa-solid fa-user-shield"></i> Admin+</span><span class="neptune-hero-pill"><i class="fa-solid fa-circle-check"></i> Active: <?=e($active['name'])?></span><span class="neptune-hero-pill"><i class="fa-solid fa-wand-magic-sparkles"></i> <?=count($customThemes)?> custom</span></div></div></section>
<?php if(isset($_GET['saved'])):?><div class="notice good">Theme applied to <?=e($u['organization_name'])?>.</div><?php endif;?><?php if(isset($_GET['theme_saved'])):?><div class="notice good">Organization theme saved.</div><?php endif;?><?php if(isset($_GET['deleted'])):?><div class="notice good">Theme deleted.</div><?php endif;?><?php if($error):?><div class="notice bad"><?=e($error)?></div><?php endif;?>
<section><div class="style-head"><div><h2>Built-in Themes</h2><p>Apply one directly or use it as a starting point.</p></div></div><div class="theme-grid">
<?php foreach($builtins as $key=>$theme):$p=$theme['palette']['dark'];$sw=[$p['bg'],$p['panel'],$p['c1-blue'],$p['accent'],$p['good'],$p['module-augur']];$on=$active['type']==='builtin'&&$active['key']===$key;?>
<article class="theme-card <?=$on?'active':''?>" <?=$on?'':'role="button" tabindex="0" data-apply-form="apply-builtin-'.e($key).'"'?>><div class="theme-top"><div><span class="theme-kind">Built-in</span><h3><?=e($theme['name'])?></h3></div><?php if($on):?><span class="pill"><i class="fa-solid fa-check"></i> Active</span><?php endif;?></div><p><?=e($theme['description'])?></p><div class="theme-swatches"><?php foreach($sw as $c):?><span style="background:<?=e($c)?>"></span><?php endforeach;?></div><div class="theme-actions"><button type="button" class="secondary customize theme-icon-action" data-source="builtin:<?=e($key)?>" title="Customize <?=e($theme['name'])?>" aria-label="Customize <?=e($theme['name'])?>"><i class="fa-solid fa-wand-magic-sparkles"></i></button></div><?php if(!$on):?><form method="post" id="apply-builtin-<?=e($key)?>" hidden><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="apply_builtin"><input type="hidden" name="theme_key" value="<?=e($key)?>"></form><?php endif;?></article>
<?php endforeach;?></div></section>
<section><div class="style-head"><div><h2><?=e($u['organization_name'])?> Themes</h2><p>Reusable themes created by your organization.</p></div><button type="button" class="secondary" id="createTheme2"><i class="fa-solid fa-plus"></i> Create Theme</button></div><?php if(!$customThemes):?><div class="card muted">No custom themes yet.</div><?php else:?><div class="theme-grid">
<?php foreach($customThemes as $theme):$p=$theme['palette']['dark'];$sw=[$p['bg'],$p['panel'],$p['c1-blue'],$p['accent'],$p['good'],$p['module-augur']];$on=$active['type']==='custom'&&(int)$active['key']===(int)$theme['id'];?>
<article class="theme-card <?=$on?'active':''?>" <?=$on?'':'role="button" tabindex="0" data-apply-form="apply-custom-'.(int)$theme['id'].'"'?>><div class="theme-top"><div><span class="theme-kind">Organization</span><h3><?=e($theme['name'])?></h3></div><?php if($on):?><span class="pill"><i class="fa-solid fa-check"></i> Active</span><?php endif;?></div><p>Updated <?=e((string)$theme['updated_at'])?></p><div class="theme-swatches"><?php foreach($sw as $c):?><span style="background:<?=e($c)?>"></span><?php endforeach;?></div><div class="theme-actions"><button type="button" class="secondary edit-theme theme-icon-action" data-id="<?=(int)$theme['id']?>" title="Edit <?=e($theme['name'])?>" aria-label="Edit <?=e($theme['name'])?>"><i class="fa-solid fa-pen"></i></button><button type="button" class="secondary duplicate-theme theme-icon-action" data-id="<?=(int)$theme['id']?>" title="Duplicate <?=e($theme['name'])?>" aria-label="Duplicate <?=e($theme['name'])?>"><i class="fa-solid fa-copy"></i></button></div><?php if(!$on):?><form method="post" id="apply-custom-<?=(int)$theme['id']?>" hidden><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="apply_custom"><input type="hidden" name="theme_id" value="<?=(int)$theme['id']?>"></form><?php endif;?></article>
<?php endforeach;?></div><?php endif;?></section>
</section>
<dialog class="theme-editor" id="themeEditor"><form method="post" id="themeForm" class="editor-shell"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_theme"><input type="hidden" name="theme_id" id="themeId"><div class="editor-head"><div><span class="theme-kind">Organization theme editor</span><h2 id="editorTitle">Create Theme</h2></div><button type="button" class="secondary" id="closeEditor"><i class="fa-solid fa-xmark"></i></button></div><div class="editor-body"><div class="editor-meta"><div><label>Theme name</label><input type="text" name="theme_name" id="themeName" maxlength="120" required placeholder="Competition Dark"></div><div id="sourceWrap"><label>Start from</label><select id="themeSource"></select></div></div><div class="editor-layout"><div class="editor-fields">
<?php foreach($darkGroups as $group=>$fields):?><section class="editor-section"><h3><?=e($group)?></h3><div class="palette-grid"><?php foreach($fields as $key=>$label):$v=$catalog['defaults']['dark'][$key];?><div class="palette-field" data-scope="dark" data-key="<?=e($key)?>"><label><?=e($label)?></label><input type="color" class="picker" value="<?=e(strlen($v)===7?$v:'#000000')?>"><input type="text" class="hex" name="dark[<?=e($key)?>]" value="<?=e($v)?>" required></div><?php endforeach;?></div></section><?php endforeach;?>
<section class="editor-section"><h3>Day Mode</h3><div class="palette-grid"><?php foreach($lightFields as $key=>$label):$v=$catalog['defaults']['light'][$key];?><div class="palette-field" data-scope="light" data-key="<?=e($key)?>"><label><?=e($label)?></label><input type="color" class="picker" value="<?=e(strlen($v)===7?$v:'#000000')?>"><input type="text" class="hex" name="light[<?=e($key)?>]" value="<?=e($v)?>" required></div><?php endforeach;?></div></section>
</div><aside class="preview"><div id="pvDark" class="preview-box"><div class="preview-card"><b>Night mode</b><div class="preview-muted">Live preview</div><div class="preview-row"><span class="preview-btn">Primary</span><span class="preview-chip">Secondary</span></div><div class="preview-swatches"><span data-color="module-trident"></span><span data-color="module-augur"></span><span data-color="module-saturn"></span><span data-color="module-vulcan"></span></div></div></div><div id="pvLight" class="preview-box"><div class="preview-card"><b>Day mode</b><div class="preview-muted">Live preview</div><div class="preview-row"><span class="preview-btn">Primary</span><span class="preview-chip">Secondary</span></div></div></div></aside></div></div><div class="editor-foot"><div class="theme-delete-zone"><button type="button" class="danger" id="deleteTheme" hidden><i class="fa-solid fa-trash"></i> Delete</button><div class="theme-delete-confirm" id="deleteThemeConfirm" hidden><span id="deleteThemeConfirmText">Delete this theme?</span><button type="button" class="secondary" id="cancelDeleteTheme">Keep Theme</button><button type="button" class="danger" id="confirmDeleteTheme"><i class="fa-solid fa-trash"></i> Delete Theme</button></div></div><div class="editor-foot-right"><button type="button" class="secondary" id="cancelEditor">Cancel</button><button type="submit" name="apply_after_save" value="0" class="secondary"><i class="fa-solid fa-floppy-disk"></i> Save</button><button type="submit" name="apply_after_save" value="1"><i class="fa-solid fa-wand-magic-sparkles"></i> Save &amp; Apply</button></div></div></form></dialog>
<form method="post" id="deleteForm" hidden><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_theme"><input type="hidden" name="theme_id" id="deleteId"></form>
<script>
(()=>{
const builtins=<?=json_encode($builtinsJs,JSON_UNESCAPED_SLASHES)?>,customs=<?=json_encode($customJs,JSON_UNESCAPED_SLASHES)?>,active=<?=json_encode(['name'=>$active['name'],'palette'=>$active['palette']],JSON_UNESCAPED_SLASHES)?>;
const dlg=document.getElementById('themeEditor'),form=document.getElementById('themeForm'),name=document.getElementById('themeName'),id=document.getElementById('themeId'),source=document.getElementById('themeSource'),sourceWrap=document.getElementById('sourceWrap'),del=document.getElementById('deleteTheme'),delId=document.getElementById('deleteId'),delForm=document.getElementById('deleteForm'),deleteConfirm=document.getElementById('deleteThemeConfirm'),deleteConfirmText=document.getElementById('deleteThemeConfirmText'),cancelDelete=document.getElementById('cancelDeleteTheme'),confirmDelete=document.getElementById('confirmDeleteTheme');
const sources={active:{name:'Current active theme',palette:active.palette},...Object.fromEntries(Object.entries(builtins).map(([k,v])=>['builtin:'+k,v])),...Object.fromEntries(Object.entries(customs).map(([k,v])=>['custom:'+k,v]))};
Object.entries(sources).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.name;source.appendChild(o)});
function field(scope,key){return form.querySelector(`.palette-field[data-scope="${scope}"][data-key="${key}"] .hex`)}
function load(p){for(const scope of ['dark','light'])for(const [k,v] of Object.entries(p[scope]||{})){const x=field(scope,k);if(!x)continue;x.value=v;const picker=x.parentElement.querySelector('.picker');if(/^#[0-9a-f]{6}$/i.test(v))picker.value=v}preview()}
function read(scope,key,fallback){return field(scope,key)?.value.trim()||fallback}
function paint(el,scope){const p=active.palette[scope];el.style.setProperty('--pv-bg',read(scope,'bg',p.bg));el.style.setProperty('--pv-bg2',read(scope,'bg2',p.bg2));el.style.setProperty('--pv-panel',read(scope,'panel',p.panel));el.style.setProperty('--pv-panel2',read(scope,'panel2',p.panel2));el.style.setProperty('--pv-line',read(scope,'line',p.line));el.style.setProperty('--pv-text',read(scope,'text',p.text));el.style.setProperty('--pv-muted',read(scope,'muted',p.muted));el.style.setProperty('--pv-primary',read(scope,'c1-blue',p['c1-blue']));el.style.setProperty('--pv-solid',read(scope,'solid-text',p['solid-text']));el.querySelectorAll('[data-color]').forEach(n=>n.style.background=read('dark',n.dataset.color,active.palette.dark[n.dataset.color]||active.palette.dark.accent))}
function preview(){paint(document.getElementById('pvDark'),'dark');paint(document.getElementById('pvLight'),'light')}
function create(src='active',suggest=''){id.value='';name.value=suggest;sourceWrap.hidden=false;del.hidden=true;deleteConfirm.hidden=true;source.value=sources[src]?src:'active';load(sources[source.value].palette);document.getElementById('editorTitle').textContent='Create Theme';dlg.showModal();setTimeout(()=>name.focus(),20)}
function edit(themeId){const t=customs[String(themeId)];if(!t)return;id.value=t.id;name.value=t.name;sourceWrap.hidden=true;del.hidden=false;deleteConfirm.hidden=true;delId.value=t.id;load(t.palette);document.getElementById('editorTitle').textContent='Edit '+t.name;dlg.showModal()}
for(const b of document.querySelectorAll('.palette-field')){const h=b.querySelector('.hex'),p=b.querySelector('.picker');h.addEventListener('input',()=>{if(/^#[0-9a-f]{6}$/i.test(h.value))p.value=h.value;preview()});p.addEventListener('input',()=>{h.value=p.value;preview()})}
document.getElementById('createTheme2').onclick=()=>create();
document.querySelectorAll('.theme-card[data-apply-form]').forEach(card=>{
 const apply=()=>{const f=document.getElementById(card.dataset.applyForm||'');if(f)f.submit()};
 card.addEventListener('click',e=>{if(e.target.closest('button,a,input,select,textarea,label'))return;apply()});
 card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();apply()}});
});
document.querySelectorAll('.customize').forEach(b=>b.onclick=e=>{e.stopPropagation();create(b.dataset.source,(sources[b.dataset.source]?.name||'Theme')+' Custom')});
document.querySelectorAll('.edit-theme').forEach(b=>b.onclick=e=>{e.stopPropagation();edit(b.dataset.id)});
document.querySelectorAll('.duplicate-theme').forEach(b=>b.onclick=e=>{e.stopPropagation();const t=customs[String(b.dataset.id)];if(t)create('custom:'+b.dataset.id,t.name+' Copy')});source.onchange=()=>load(sources[source.value].palette);document.getElementById('closeEditor').onclick=()=>dlg.close();document.getElementById('cancelEditor').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});del.onclick=()=>{const t=customs[String(delId.value)];if(!t)return;deleteConfirmText.textContent=`Delete "${t.name}"? This cannot be undone.`;del.hidden=true;deleteConfirm.hidden=false};cancelDelete.onclick=()=>{deleteConfirm.hidden=true;del.hidden=false};confirmDelete.onclick=()=>{const t=customs[String(delId.value)];if(!t)return;confirmDelete.disabled=true;confirmDelete.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Deleting…';delForm.submit()};preview();
})();
</script>
<?php include dirname(__DIR__).'/partials_footer.php';?>
