-- Neptune EPA v2
-- Four game-agnostic EPA streams built from The Blue Alliance match results: overall, autonomous, teleop, and endgame.
-- AUGUR EPA (the scouting-enhanced blend) is calculated at request time inside authenticated Neptune and is not stored/exposed here.

CREATE TABLE IF NOT EXISTS augur_epa_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  event_id BIGINT UNSIGNED NOT NULL,
  season_year SMALLINT UNSIGNED NOT NULL,
  frc_team_number INT UNSIGNED NOT NULL,
  rating DECIMAL(10,3) NOT NULL DEFAULT 0,
  auto_rating DECIMAL(10,3) NULL,
  teleop_rating DECIMAL(10,3) NULL,
  endgame_rating DECIMAL(10,3) NULL,
  trend DECIMAL(10,3) NOT NULL DEFAULT 0,
  sigma DECIMAL(10,3) NOT NULL DEFAULT 0,
  confidence DECIMAL(6,2) NOT NULL DEFAULT 0,
  matches_played SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  wins SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  losses SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ties SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  tba_rank SMALLINT UNSIGNED NULL,
  source_event_key VARCHAR(40) NULL,
  model_version VARCHAR(40) NOT NULL DEFAULT 'neptune-epa-v2',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_augur_epa_event_team (organization_id,event_id,frc_team_number),
  KEY idx_augur_epa_event_rank (organization_id,event_id,rating),
  KEY idx_augur_epa_event_year_team (organization_id,season_year,frc_team_number),
  CONSTRAINT fk_augur_epa_event_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_augur_epa_event_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS augur_epa_season (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  season_year SMALLINT UNSIGNED NOT NULL,
  frc_team_number INT UNSIGNED NOT NULL,
  rating DECIMAL(10,3) NOT NULL DEFAULT 0,
  auto_rating DECIMAL(10,3) NULL,
  teleop_rating DECIMAL(10,3) NULL,
  endgame_rating DECIMAL(10,3) NULL,
  trend DECIMAL(10,3) NOT NULL DEFAULT 0,
  sigma DECIMAL(10,3) NOT NULL DEFAULT 0,
  confidence DECIMAL(6,2) NOT NULL DEFAULT 0,
  events_played SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  matches_played SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  wins SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  losses SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ties SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  last_event_id BIGINT UNSIGNED NULL,
  model_version VARCHAR(40) NOT NULL DEFAULT 'neptune-epa-v2',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_augur_epa_season_team (organization_id,season_year,frc_team_number),
  KEY idx_augur_epa_season_rank (organization_id,season_year,rating),
  CONSTRAINT fk_augur_epa_season_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_augur_epa_season_event FOREIGN KEY (last_event_id) REFERENCES events(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS augur_epa_match (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  organization_id BIGINT UNSIGNED NOT NULL,
  event_id BIGINT UNSIGNED NOT NULL,
  season_year SMALLINT UNSIGNED NOT NULL,
  tba_match_key VARCHAR(60) NOT NULL,
  match_number SMALLINT UNSIGNED NOT NULL,
  frc_team_number INT UNSIGNED NOT NULL,
  alliance ENUM('Red','Blue') NOT NULL,
  pre_rating DECIMAL(10,3) NOT NULL,
  post_rating DECIMAL(10,3) NOT NULL,
  rating_delta DECIMAL(10,3) NOT NULL DEFAULT 0,
  pre_auto_rating DECIMAL(10,3) NULL,
  post_auto_rating DECIMAL(10,3) NULL,
  pre_teleop_rating DECIMAL(10,3) NULL,
  post_teleop_rating DECIMAL(10,3) NULL,
  pre_endgame_rating DECIMAL(10,3) NULL,
  post_endgame_rating DECIMAL(10,3) NULL,
  pre_sigma DECIMAL(10,3) NOT NULL DEFAULT 0,
  post_sigma DECIMAL(10,3) NOT NULL DEFAULT 0,
  model_version VARCHAR(40) NOT NULL DEFAULT 'neptune-epa-v2',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_augur_epa_match_team (organization_id,event_id,tba_match_key,frc_team_number),
  KEY idx_augur_epa_match_history (organization_id,event_id,frc_team_number,match_number),
  CONSTRAINT fk_augur_epa_match_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_augur_epa_match_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
